# This file has been auto-generated by i3-config-wizard(1).
# It will not be overwritten, so edit it as you like.
#
# Should you change your keyboard layout somewhen, delete
# this file and re-run i3-config-wizard(1).
#

# i3 config file (v4)
#
# Please see http://i3wm.org/docs/userguide.html for a complete reference!

set $mod Mod4

# font for window titles. ISO 10646 = Unicode
# font -misc-fixed-medium-r-normal--13-120-75-75-C-70-iso10646-1
font pango:Tewi 8

exec_always ~/.xsession

# Use Mouse+$mod to drag floating windows to their wanted position
floating_modifier $mod

# start a terminal
bindsym $mod+Return exec urxvtc

# kill focused window
bindsym $mod+Shift+Q kill

# start dmenu (a program launcher)
bindsym $mod+d exec dmenu_run

# change focus
bindsym $mod+j focus left
bindsym $mod+k focus down
bindsym $mod+l focus up
bindsym $mod+eacute focus right

# alternatively, you can use the cursor keys:
bindsym $mod+Left focus left
bindsym $mod+Down focus down
bindsym $mod+Up focus up
bindsym $mod+Right focus right

# move focused window
bindsym $mod+Shift+J move left
bindsym $mod+Shift+K move down
bindsym $mod+Shift+L move up
bindsym $mod+Shift+Eacute move right

# alternatively, you can use the cursor keys:
bindsym $mod+Shift+Left move left
bindsym $mod+Shift+Down move down
bindsym $mod+Shift+Up move up
bindsym $mod+Shift+Right move right

# split in horizontal orientation
bindsym $mod+h split h

# split in vertical orientation
bindsym $mod+v split v

# enter fullscreen mode for the focused container
bindsym $mod+f fullscreen

# change container layout (stacked, tabbed, default)
bindsym $mod+s layout stacking
bindsym $mod+w layout tabbed
bindsym $mod+e layout default

# toggle tiling / floating
bindsym $mod+Shift+space floating toggle

# change focus between tiling / floating windows
bindsym $mod+space focus mode_toggle

# focus the parent container
bindsym $mod+a focus parent

# focus the child container
#bindcode $mod+d focus child

# switch to workspace
bindsym $mod+1 workspace 1:www
bindsym $mod+2 workspace 2:chat
bindsym $mod+3 workspace 3:dev
bindsym $mod+4 workspace 4:vim
bindsym $mod+5 workspace 5
bindsym $mod+6 workspace 6
bindsym $mod+7 workspace 7
bindsym $mod+8 workspace 8
bindsym $mod+9 workspace 9:vlc
bindsym $mod+odiaeresis workspace 10

# move focused container to workspace
bindsym $mod+Shift+apostrophe move workspace 1:www
bindsym $mod+Shift+quotedbl move workspace 2:chat
bindsym $mod+Shift+plus move workspace 3:dev
bindsym $mod+Shift+exclam move workspace 4:vim
bindsym $mod+Shift+percent move workspace 5
bindsym $mod+Shift+slash move workspace 6
bindsym $mod+Shift+equal move workspace 7
bindsym $mod+Shift+parenleft move workspace 8
bindsym $mod+Shift+parenright move workspace 9:vlc
bindsym $mod+Shift+Odiaeresis move workspace 10

# assign programs
assign [class="Google-chrome"] → 1:www
assign [class="Gvim"] → 4:vim
assign [class="Vlc"] → 9:vlc

# reload the configuration file
bindsym $mod+Shift+C reload
# restart i3 inplace (preserves your layout/session, can be used to upgrade i3)
bindsym $mod+Shift+R restart
# exit i3 (logs you out of your X session)
bindsym $mod+Shift+E exit

# resize window (you can also use the mouse for that)
mode "resize" {
        # These bindings trigger as soon as you enter the resize mode

        # They resize the border in the direction you pressed, e.g.
        # when pressing left, the window is resized so that it has
        # more space on its left

bindsym j resize shrink left 10 px or 10 ppt
bindsym Shift+J resize grow   left 10 px or 10 ppt

bindsym k resize shrink down 10 px or 10 ppt
bindsym Shift+K resize grow   down 10 px or 10 ppt

bindsym l resize shrink up 10 px or 10 ppt
bindsym Shift+L resize grow   up 10 px or 10 ppt

bindsym eacute resize shrink right 10 px or 10 ppt
bindsym Shift+Eacute resize grow   right 10 px or 10 ppt

        # same bindings, but for the arrow keys
bindsym Left resize shrink left 10 px or 10 ppt
bindsym Shift+Left resize grow   left 10 px or 10 ppt

bindsym Down resize shrink down 10 px or 10 ppt
bindsym Shift+Down resize grow   down 10 px or 10 ppt

bindsym Up resize shrink up 10 px or 10 ppt
bindsym Shift+Up resize grow   up 10 px or 10 ppt

bindsym Right resize shrink right 10 px or 10 ppt
bindsym Shift+Right resize grow   right 10 px or 10 ppt

        # back to normal: Enter or Escape
bindsym Return mode "default"
bindsym Escape mode "default"
}

bindsym $mod+r mode "resize"

mode "move" {
  bindsym Up move up 20px
  bindsym Left move left 20px
  bindsym Down move down 20px
  bindsym Right move right 20px
  bindsym Mod4+m mode "default"
}

bindsym Mod4+m focus floating; mode "move"

client.focused          #9fbc00 #9fbc00  #111111
client.unfocused        #444444 #444444  #315858
client.focused_inactive #444444 #444444  #2c2c2f
client.urgent           #383a3b #383a3b  #ee0000

# Start i3bar to display a workspace bar (plus the system information i3status
# finds out, if available)
bar {
  status_command /home/picard/projects/fun/haskell/i3/status
  position top
  colors {
    statusline  #999999
    background  #252525
    focused_workspace  #292929    #292929   #cccccc
    active_workspace   #252525    #252525   #696f89
    inactive_workspace #252525    #252525     #6b6b6b 
    urgent_workspace   #252525    #252525   #c7a551
  }
}

# bindsym XF86AudioLowerVolume exec --no-startup-id ~/.i3/volman/adjust 1 -10
# bindsym XF86AudioRaiseVolume exec --no-startup-id ~/.i3/volman/adjust 1 10
# bindsym XF86AudioMute exec --no-startup-id ~/.i3/volman/toggle 1
bindsym XF86AudioPlay exec mpc toggle
bindsym XF86AudioNext exec mpc next
bindsym XF86AudioPrev exec mpc prev
bindsym Print exec gnome-screenshot -i
 
workspace_auto_back_and_forth yes

# lock screen 
bindsym Ctrl+Mod1+l exec i3lock -d

# shutdown dialog
# bindsym Ctrl+Mod1+Delete exec shutdown-dialog
